namespace TgimbaSeleniumTests.Tests
{
    public class Constants
    {        
        public const string TEST_USER = "testUser";
        public const string DB_CONN_LOCAL_HOST_MASTER = "Data Source=localhost;Initial Catalog=master;Integrated Security=true;";
        public const string DB_CONN_LOCAL_HOST_BUCKETLIST = "Data Source=localhost;Initial Catalog=BucketList;Integrated Security=true;";
        
        public const string DROP_DB = " EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'BucketList' " 
                                    + " ALTER DATABASE[BucketList] SET SINGLE_USER WITH ROLLBACK IMMEDIATE "
                                    + " DROP DATABASE [BucketList]  ";
        public const string DELETE_TEST_USER = "delete from [Bucket].[BucketListItem]   "
                                        + " where bucketlistitemid in (select bucketListItemId   "
                                        + "                            from [Bucket].[BucketListUser]   "
                                        + " 						   where userid in (select userid   "
                                        + " 						                    from [Bucket].[User]   "
                                        + " 										    where UserName = 'testUser')   "
                                        + " 						   )   "
                                        + "    "
                                        + " delete from [Bucket].[BucketListUser]   "
                                        + " where userid in (select userid   "
                                        + " 				from [Bucket].[User]   "
                                        + " 				where UserName = 'testUser')   "
                                        + "    "
                                        + " delete from [Bucket].[User]   "
                                        + " where UserName = 'testUser' ";
        public const string CREATE_TABLE = "CREATE TABLE [Bucket].[BrowserCapability](  "
                                        + " [BrowserCapabilityId] [bigint] IDENTITY(1,1) NOT NULL,  "
                                        + " [BrowserLogId] [bigint] NULL,  "
                                        + " [Key] [varchar](100) NULL,  "
                                        + " [Value] [varchar](500) NULL,  "
                                        + " CONSTRAINT [PK_BrowserCapability] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[BrowserCapabilityId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                        + " CREATE TABLE [Bucket].[BucketListItem](  "
                                        + " 	[BucketListItemId] [int] IDENTITY(1,1) NOT NULL,  "
                                        + " 	[ListItemName] [nvarchar](max) NULL,  "
                                        + " 	[Created] [datetime] NULL,  "
                                        + " 	[Category] [nvarchar](255) NULL,  "
                                        + " 	[Achieved] [bit] NULL,  "
                                        + " 	[CategorySortOrder] [int] NULL,  "
                                        + "  CONSTRAINT [PK_BucketListItems] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[BucketListItemId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                        + " CREATE TABLE [Bucket].[BucketListUser](  "
                                        + " 	[BucketListUserId] [int] IDENTITY(1,1) NOT NULL,  "
                                        + " 	[BucketListItemId] [int] NULL,  "
                                        + " 	[UserId] [int] NULL,  "
                                        + "  CONSTRAINT [PK_BucketListUser] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[BucketListUserId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                        + " CREATE TABLE [Bucket].[User](  "
                                        + " 	[UserId] [int] IDENTITY(1,1) NOT NULL,  "
                                        + " 	[UserName] [nvarchar](255) NULL,  "
                                        + " 	[Salt] [nvarchar](max) NULL,  "
                                        + " 	[PassWord] [nvarchar](max) NULL,  "
                                        + " 	[Email] [nvarchar](255) NULL,  "
                                        + " 	[Token] [nvarchar](1000) NULL,  "
                                        + " 	[Created] [datetime] NULL,  "
                                        + " 	[CreatedBy] [nvarchar](255) NULL,  "
                                        + " 	[Modified] [datetime] NULL,  "
                                        + " 	[ModifiedBy] [nvarchar](255) NULL,  "
                                        + "  CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[UserId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                         + " CREATE TABLE [Bucket].[Log](  "
                                         + "	[LogId] [bigint] IDENTITY(1,1) NOT NULL,  "
                                         + "	[LogMessage] [nvarchar](max) NULL,  "
                                         + "	[Created] [datetime] NULL,  "
                                         + " CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED   "
                                         + "(  "
                                         + "	[LogId] ASC  "
                                         + ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                         + ") ON [PRIMARY] TEXTIMAGE_ON [PRIMARY] ";

        public const string CREATE_SCHEMA = "create schema Bucket";
        public const string CREATE_DB = "CREATE DATABASE [BucketList] ";
    }
}
