using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TgimbaSeleniumTests.Tests
{
    public class Constants
    {        
        public const string TEST_USER = "testUser";
        public const string DB_CONN = "";
        public const string DB_CONN_LOCAL_HOST_MASTER = "";
        public const string DB_CONN_LOCAL_HOST_BUCKETLIST = "";
        
        public const string DROP_DB = "DROP DATABASE [BucketList] ";
        public const string DELETE_TEST_USER = "delete from [Bucket].[BucketListItem]   "
                                        + " where bucketlistitemid in (select bucketListItemId   "
                                        + "                            from [Bucket].[BucketListUser]   "
                                        + " 						   where userid in (select userid   "
                                        + " 						                    from [Bucket].[User]   "
                                        + " 										    where UserName = 'testUser')   "
                                        + " 						   )   "
                                        + "    "
                                        + " delete from [Bucket].[BucketListUser]   "
                                        + " where userid in (select userid   "
                                        + " 				from [Bucket].[User]   "
                                        + " 				where UserName = 'testUser')   "
                                        + "    "
                                        + " delete from [Bucket].[User]   "
                                        + " where UserName = 'testUser' ";
        public const string CREATE_TABLE = "CREATE TABLE [Bucket].[BrowserCapability](  "
                                        + " [BrowserCapabilityId] [bigint] IDENTITY(1,1) NOT NULL,  "
                                        + " [BrowserLogId] [bigint] NULL,  "
                                        + " [Key] [varchar](100) NULL,  "
                                        + " [Value] [varchar](500) NULL,  "
                                        + " CONSTRAINT [PK_BrowserCapability] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[BrowserCapabilityId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                        + " CREATE TABLE [Bucket].[BucketListItem](  "
                                        + " 	[BucketListItemId] [int] IDENTITY(1,1) NOT NULL,  "
                                        + " 	[ListItemName] [nvarchar](max) NULL,  "
                                        + " 	[Created] [datetime] NULL,  "
                                        + " 	[Category] [nvarchar](255) NULL,  "
                                        + " 	[Achieved] [bit] NULL,  "
                                        + " 	[CategorySortOrder] [int] NULL,  "
                                        + "  CONSTRAINT [PK_BucketListItems] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[BucketListItemId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                        + " CREATE TABLE [Bucket].[BucketListUser](  "
                                        + " 	[BucketListUserId] [int] IDENTITY(1,1) NOT NULL,  "
                                        + " 	[BucketListItemId] [int] NULL,  "
                                        + " 	[UserId] [int] NULL,  "
                                        + "  CONSTRAINT [PK_BucketListUser] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[BucketListUserId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                        + " CREATE TABLE [Bucket].[User](  "
                                        + " 	[UserId] [int] IDENTITY(1,1) NOT NULL,  "
                                        + " 	[UserName] [nvarchar](255) NULL,  "
                                        + " 	[Salt] [nvarchar](max) NULL,  "
                                        + " 	[PassWord] [nvarchar](max) NULL,  "
                                        + " 	[Email] [nvarchar](255) NULL,  "
                                        + " 	[Token] [nvarchar](1000) NULL,  "
                                        + " 	[Created] [datetime] NULL,  "
                                        + " 	[CreatedBy] [nvarchar](255) NULL,  "
                                        + " 	[Modified] [datetime] NULL,  "
                                        + " 	[ModifiedBy] [nvarchar](255) NULL,  "
                                        + "  CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED   "
                                        + " (  "
                                        + " 	[UserId] ASC  "
                                        + " )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                        + " ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]  "
                                        + "   "
                                        + "   "
                                         + " CREATE TABLE [Bucket].[Log](  "
                                         + "	[LogId] [bigint] IDENTITY(1,1) NOT NULL,  "
                                         + "	[LogMessage] [nvarchar](max) NULL,  "
                                         + "	[Created] [datetime] NULL,  "
                                         + " CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED   "
                                         + "(  "
                                         + "	[LogId] ASC  "
                                         + ")WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  "
                                         + ") ON [PRIMARY] TEXTIMAGE_ON [PRIMARY] ";

        public const string CREATE_SCHEMA = "create schema Bucket";
        public const string CREATE_DB = "CREATE DATABASE [BucketList]  "
                                     + " CONTAINMENT = NONE  "
                                     + "  ON  PRIMARY   "
                                     + " ( NAME = N'BucketList', FILENAME = N'C:\\Program Files\\Microsoft SQL Server\\MSSQL12.MSSQLSERVER\\MSSQL\\DATA\\BucketList.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )  "
                                     + "  LOG ON   "
                                     + " ( NAME = N'BucketList_log', FILENAME = N'C:\\Program Files\\Microsoft SQL Server\\MSSQL12.MSSQLSERVER\\MSSQL\\DATA\\BucketList_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)  "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET COMPATIBILITY_LEVEL = 120  "
                                     + "   "
                                     + "   "
                                     + " IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))  "
                                     + " begin  "
                                     + " EXEC [BucketList].[dbo].[sp_fulltext_database] @action = 'enable'  "
                                     + " end  "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET ANSI_NULL_DEFAULT OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET ANSI_NULLS OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET ANSI_PADDING OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET ANSI_WARNINGS OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET ARITHABORT OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET AUTO_CLOSE OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET AUTO_SHRINK OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET AUTO_UPDATE_STATISTICS ON   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET CURSOR_CLOSE_ON_COMMIT OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET CURSOR_DEFAULT  GLOBAL   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET CONCAT_NULL_YIELDS_NULL OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET NUMERIC_ROUNDABORT OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET QUOTED_IDENTIFIER OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET RECURSIVE_TRIGGERS OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET  DISABLE_BROKER   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET AUTO_UPDATE_STATISTICS_ASYNC OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET DATE_CORRELATION_OPTIMIZATION OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET TRUSTWORTHY OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET ALLOW_SNAPSHOT_ISOLATION OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET PARAMETERIZATION SIMPLE   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET READ_COMMITTED_SNAPSHOT OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET HONOR_BROKER_PRIORITY OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET RECOVERY FULL   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET  MULTI_USER   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET PAGE_VERIFY CHECKSUM    "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET DB_CHAINING OFF   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET TARGET_RECOVERY_TIME = 0 SECONDS   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET DELAYED_DURABILITY = DISABLED   "
                                     + "   "
                                     + "   "
                                     + " ALTER DATABASE [BucketList] SET  READ_WRITE  "
                                     + "   ";

    }
}
